# Generated by Django 5.2.4 on 2025-07-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESS', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=12),
        ),
    ]
