# Generated by Django 5.2.4 on 2025-07-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_alter_estimatejob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatejob',
            name='uploads',
        ),
        migrations.AddField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='4a7caf6d072543cea1a3c2343629af6c', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='estimatejob',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('fire', 'Fire'), ('wind', 'Wind')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='estimatejob',
            name='property_type',
            field=models.CharField(blank=True, choices=[('res', 'Residential'), ('com', 'Commercial')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='status',
            field=models.CharField(default='PENDING', max_length=12),
        ),
    ]
