# Generated by Django 5.2.4 on 2025-07-20 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0003_remove_estimatejob_uploads_estimatejob_claim_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='2f18c78055a04a16baa506e4041b3a3c', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
