# Generated by Django 5.2.4 on 2025-08-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0004_alter_estimatejob_claim_number_alter_upload_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='ce6580df7ca84c2d9ed8ea7009044e38', max_length=32, null=True),
        ),
    ]
