# Generated by Django 5.2.4 on 2025-08-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0005_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='d9992b733b914064b1c5603d4befbbab', max_length=32, null=True),
        ),
    ]
