# Generated by Django 5.2.4 on 2025-08-04 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0006_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='estimate.estimatejob'),
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='8fa9097a1c4a4924a3c131144f41418c', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='%Y/%m/'),
        ),
    ]
