# Generated by Django 5.2.4 on 2025-08-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0007_upload_job_alter_estimatejob_claim_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatejob',
            name='instructions',
            field=models.TextField(default='', help_text='User’s description of the damage, context, etc.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='d798a34b0e5c4cea82c2bfe13fddf20a', max_length=32, null=True),
        ),
    ]
