# Generated by Django 5.2.4 on 2025-08-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0008_estimatejob_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='84e3f4847f7c46b585809f0e3e208d9a', max_length=32, null=True),
        ),
    ]
