# Generated by Django 5.2.4 on 2025-08-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0010_alter_estimatejob_claim_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='f01e0ab38ccf439a8f49b9ef370c86b1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='estimateresult',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estimate.estimatejob'),
        ),
    ]
