# Generated by Django 5.2.4 on 2025-08-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0011_remove_estimateresult_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='da1ec804c7cf41ffaee45b4ece80e5aa', max_length=32, null=True),
        ),
    ]
