# Generated by Django 5.2.4 on 2025-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0012_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateresult',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='estimates/'),
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='496930c3a1ba4ea087c17fe82599e68c', max_length=32, null=True),
        ),
    ]
