# Generated by Django 5.2.4 on 2025-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0013_estimateresult_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatejob',
            name='guest_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='estimateresult',
            name='guest_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='guest_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='5123c59464b3469d9a388223fa492dd7', max_length=32, null=True),
        ),
    ]
