# Generated by Django 5.2.4 on 2025-08-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0014_estimatejob_guest_key_estimateresult_guest_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='f82faf8de6fa4489b38acf859f338226', max_length=32, null=True),
        ),
    ]
