# Generated by Django 5.2.4 on 2025-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0015_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='a9cc9af48da04ce49395870118bcacdb', max_length=32, null=True),
        ),
    ]
