# Generated by Django 5.2.4 on 2025-08-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0016_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='29e30968f54441fdb2608e667f2cc8d8', max_length=32, null=True),
        ),
    ]
