# Generated by Django 5.2.4 on 2025-08-22 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0017_alter_estimatejob_claim_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimateresult',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='a3d8b1a1aec14975899bff0faa2725c9', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='estimateresult',
            name='guest_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='estimateresult',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estimateresult', serialize=False, to='estimate.estimatejob'),
        ),
        migrations.AlterField(
            model_name='estimateresult',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='estimateresult',
            name='raw_json',
            field=models.JSONField(default=dict),
        ),
    ]
