# Generated by Django 5.2.4 on 2025-08-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0018_estimateresult_created_estimateresult_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='3751c1bdd8eb4556a4a9a8f10dff2fdc', max_length=32, null=True),
        ),
    ]
