# Generated by Django 5.2.4 on 2025-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0019_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='12cfbe51ab454215a7ce5918c4a5166e', max_length=32, null=True),
        ),
    ]
