# Generated by Django 5.2.4 on 2025-08-23 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0021_alter_estimatejob_claim_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='b1454c4652cd4f428b5c1fabbbcb320f', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='estimateresult',
            name='guest_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='estimateresult',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimateresult',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
