# Generated by Django 5.2.4 on 2025-08-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0022_alter_estimatejob_claim_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='e0f46818c7fa4a12a5f939a1961d68d9', max_length=32, null=True),
        ),
    ]
