# Generated by Django 5.2.4 on 2025-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0023_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatejob',
            name='agent_kind',
            field=models.CharField(choices=[('insurance', 'insurance'), ('home_project', 'home_project'), ('contractor', 'contractor')], default='insurance', max_length=32),
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='b8ba834f5f12471ba21d841149b341fc', max_length=32, null=True),
        ),
    ]
