# Generated by Django 5.2.4 on 2025-09-05 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0024_estimatejob_agent_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='7752321ae8f0430c883dc718e1a208d5', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='ContractorSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zip', models.CharField(max_length=10)),
                ('trades', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=12)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_searches', to='estimate.estimatejob')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
