# Generated by Django 5.2.4 on 2025-09-06 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0025_alter_estimatejob_claim_number_contractorsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='dfd1c64d8e244b4a81c6aa4486ded781', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('zip', models.CharField(max_length=12)),
                ('guest_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estimatejob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='estimate.project'),
        ),
        migrations.DeleteModel(
            name='ContractorSearch',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'created'], name='estimate_pr_owner_i_5bc8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['guest_key', 'created'], name='estimate_pr_guest_k_6f21a1_idx'),
        ),
    ]
