# Generated by Django 5.2.4 on 2025-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0026_alter_estimatejob_claim_number_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatejob',
            name='title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]

