# Generated by Django 5.2.4 on 2025-09-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0027_estimatejob_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatejob',
            name='project_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='estimatejob',
            constraint=models.UniqueConstraint(fields=('project', 'project_seq'), name='uniq_job_project_seq'),
        ),
    ]

