# Generated by Django 5.2.4 on 2025-09-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0028_estimatejob_project_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateresult',
            name='inventory',
            field=models.JSONField(blank=True, default=list),
        ),
    ]

