# Generated by Django 5.2.4 on 2025-09-06 16:15

from django.db import migrations, models


def backfill_work_grade(apps, schema_editor):
    EstimateJob = apps.get_model('estimate', 'EstimateJob')
    # Default any existing rows to 'standard' if unset
    EstimateJob.objects.filter(work_grade__isnull=True).update(work_grade='standard')


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0029_estimateresult_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatejob',
            name='work_grade',
            field=models.CharField(blank=True, choices=[('low', 'Low end'), ('standard', 'Standard'), ('high', 'High end')], help_text='Material/finish level', max_length=9, null=True),
        ),
        migrations.RunPython(backfill_work_grade, migrations.RunPython.noop),
    ]

