# Generated by Django 5.2.4 on 2025-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0030_estimatejob_work_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateresult',
            name='inventory_status',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='IDLE', help_text='Background status for inventory generation', max_length=10),
        ),
        migrations.AddField(
            model_name='estimateresult',
            name='inventory_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='estimateresult',
            name='inventory_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

