# Generated by Django 5.2.4 on 2025-09-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0030_estimatejob_work_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created', '-id']},
        ),
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='b477de5831bf43809e0d881dd1d6c796', max_length=32, null=True),
        ),
    ]
