# Generated by Django 5.2.4 on 2025-09-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0031_alter_project_options_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatejob',
            name='claim_number',
            field=models.CharField(blank=True, default='affe72a9244244279d33b95153151f10', max_length=32, null=True),
        ),
    ]
