# Generated by Django to relax NOT NULL on inventory_status after rollback

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0032_alter_estimatejob_claim_number'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DO $$\n"
                "BEGIN\n"
                "  IF EXISTS (\n"
                "    SELECT 1 FROM information_schema.columns\n"
                "    WHERE table_name='estimate_estimateresult' AND column_name='inventory_status'\n"
                "  ) THEN\n"
                "    ALTER TABLE estimate_estimateresult ALTER COLUMN inventory_status DROP NOT NULL;\n"
                "    ALTER TABLE estimate_estimateresult ALTER COLUMN inventory_status SET DEFAULT 'IDLE';\n"
                "  END IF;\n"
                "END$$;"
            ),
            reverse_sql=(
                "DO $$\n"
                "BEGIN\n"
                "  IF EXISTS (\n"
                "    SELECT 1 FROM information_schema.columns\n"
                "    WHERE table_name='estimate_estimateresult' AND column_name='inventory_status'\n"
                "  ) THEN\n"
                "    ALTER TABLE estimate_estimateresult ALTER COLUMN inventory_status DROP DEFAULT;\n"
                "    ALTER TABLE estimate_estimateresult ALTER COLUMN inventory_status SET NOT NULL;\n"
                "  END IF;\n"
                "END$$;"
            ),
        ),
    ]
