# Generated by hand: contractor lead hub models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimate", "0033_relax_inventory_status_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("headline", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("appendix", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("open", "Open"), ("matched", "Matched"), ("closed", "Closed")], default="open", max_length=16)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job", models.OneToOneField(on_delete=models.CASCADE, related_name="contractor_lead", to="estimate.estimatejob")),
                ("result", models.OneToOneField(on_delete=models.CASCADE, related_name="contractor_lead", to="estimate.estimateresult")),
            ],
            options={
                "ordering": ("-posted_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ContractorLeadResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("decision", models.CharField(choices=[("available", "Available"), ("declined", "Declined")], default="available", max_length=16)),
                ("note", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("contractor", models.ForeignKey(on_delete=models.CASCADE, related_name="contractor_lead_responses", to=settings.AUTH_USER_MODEL)),
                ("lead", models.ForeignKey(on_delete=models.CASCADE, related_name="responses", to="estimate.contractorlead")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="contractorleadresponse",
            unique_together={("lead", "contractor")},
        ),
    ]
