# Generated by hand: rename EstimateResult.premium to total_cost
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimate", "0034_contractor_leads"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estimateresult",
            old_name="premium",
            new_name="total_cost",
        ),
        migrations.AlterField(
            model_name="estimateresult",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
