# Generated by hand: add User.role and contractor models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_free_jobs_granted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('contractor', 'Contractor'), ('adjuster', 'Adjuster')], default='user', max_length=24),
        ),

        migrations.CreateModel(
            name='ContractorTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),

        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, blank=True)),
                ('photo', models.ImageField(upload_to='contractors/photos/%Y/%m/', blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('address_line1', models.CharField(max_length=160, blank=True)),
                ('address_line2', models.CharField(max_length=160, blank=True)),
                ('city', models.CharField(max_length=80, blank=True)),
                ('state', models.CharField(max_length=40, blank=True)),
                ('postal_code', models.CharField(max_length=20, blank=True)),
                ('country', models.CharField(max_length=2, blank=True)),
                ('bio', models.TextField(blank=True)),
                ('identity_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('identity_note', models.TextField(blank=True)),
                ('identity_number', models.TextField(blank=True, null=True)),
                ('identity_document', models.FileField(upload_to='contractors/id_docs/%Y/%m/', blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to='accounts.user')),
                ('tags', models.ManyToManyField(blank=True, related_name='contractors', to='accounts.ContractorTag')),
            ],
        ),
    ]
