# Generated by hand: add name fields to ContractorProfile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_role_and_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='commercial_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
