# Generated by Django 5.2.4 on 2025-09-18 19:11

import accounts.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_contractor_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorprofile",
            name="commercial_name",
            field=models.CharField(
                blank=True, help_text="Business/trade name", max_length=160
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="identity_document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url=None,
                    location="/Users/yotamabraham/Desktop/ai-insurance/private_media",
                ),
                upload_to="contractors/id_docs/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="identity_number",
            field=accounts.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="years_experience",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(80),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contractortag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
