# Generated by hand: add contractor application fields
from django.db import migrations, models
import django.contrib.postgres.fields
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_contractorprofile_commercial_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractorprofile",
            name="commercial_name",
        ),
        migrations.RemoveField(
            model_name="contractorprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="contractorprofile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="availability",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="attachment",
            field=models.FileField(blank=True, null=True, storage=accounts.models.private_storage, upload_to="contractors/applications/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="bonded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="company",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="how_heard",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="insured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="project_sizes",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="project_types",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="trades",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="zip_codes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="years_experience",
            field=models.CharField(blank=True, choices=[("<1", "Less than 1 year"), ("1-3", "1-3 years"), ("3-5", "3-5 years"), ("5-10", "5-10 years"), ("10+", "10+ years")], default="", max_length=8),
        ),
    ]
